# Generated by Django 5.2.8 on 2026-01-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sex',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
