# Generated by Django 5.2.8 on 2026-01-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_sex_alter_lead_full_name_alter_lead_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='job',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
