# Generated by Django 5.2.8 on 2026-03-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_job_alter_lead_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='job',
        ),
    ]
